# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
r:
- 3.3.0
- 3.4
- 3.5
- devel
osx_image: xcode9 

os: 
  - linux
  - osx 

before_install: 
  - if [[ "${TRAVIS_OS_NAME}" = 'osx' ]]; 
    then 
      sudo chown -R $(whoami) /usr/local/share/man/man7 ;
      brew update;
      brew install -v libgit2; 
    fi